apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgre
  namespace: postgre
spec:
  destination:
    namespace: postgre
    server: https://kubernetes.default.svc
  project: default
  source:
    path: postgre
    repoURL: https://github.com/hozun/argo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
